// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAycnVtcCzZfljAk_0NFKqGDfgRx9FfB2A',
    appId: '1:695250858260:web:014f265526631052b69201',
    messagingSenderId: '695250858260',
    projectId: 'parking-management-proje-d41a0',
    authDomain: 'parking-management-proje-d41a0.firebaseapp.com',
    storageBucket: 'parking-management-proje-d41a0.appspot.com',
    measurementId: 'G-T1EYB09X2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn3GrUGZUQeUcdpKkCwPe6yvGLwOEioXg',
    appId: '1:695250858260:android:929e3d6ed76fab39b69201',
    messagingSenderId: '695250858260',
    projectId: 'parking-management-proje-d41a0',
    storageBucket: 'parking-management-proje-d41a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0rW3dnneoPINpxiyvLFnmZ3WBdgv-S7I',
    appId: '1:695250858260:ios:557d77540d201334b69201',
    messagingSenderId: '695250858260',
    projectId: 'parking-management-proje-d41a0',
    storageBucket: 'parking-management-proje-d41a0.appspot.com',
    iosBundleId: 'com.example.parckingManagement',
  );
}
